version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka
    ports:
      - 22181:2181
    volumes:
      - zookeeper1_data:/var/lib/zookeeper/data
      - zookeeper1_log:/var/lib/zookeeper/log

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka
    ports:
      - 32181:2181
    volumes:
      - zookeeper1_data:/var/lib/zookeeper/data
      - zookeeper1_log:/var/lib/zookeeper/log

  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    depends_on:
      - zookeeper-1
      - zookeeper-2
    networks:
      - kafka
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LOG_RETENTION_MINUTES: 1 # delete logs every minute
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - ./kafka-data1:/kafka/kafka-logs

  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    networks:
      - kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LOG_RETENTION_MINUTES: 1 # delete logs every minute
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - ./kafka-data2:/kafka/kafka-logs

  kafka-ui:
    image: 'obsidiandynamics/kafdrop'
    container_name: 'kafka-web-ui'
    networks:
      - kafka
    environment:
      - KAFKA_BROKERCONNECT=kafka-1:9092,kafka-2:9092
      - SERVER_PORT=8080
    ports:
      - '8080:8080'
    depends_on:
      - kafka-1
      - kafka-2
      - zookeeper-1
      - zookeeper-2

networks:
  kafka:

volumes:
  zookeeper1_data:
  zookeeper1_log:
# ---

# version: '3.7'

# x-zooServers: &zooServers zoo-1:12888:13888;zoo-2:22888:23888;zoo-3:32888:33888
# x-kafkaZookeeperConnect: &kafkaZookeeperConnect zoo-1:12181,zoo-2:22181,zoo-3:32181

# services:

#   # Zookeeper servers and Kafka servers
#   zoo-1:
#     image: confluentinc/cp-zookeeper:latest
#     hostname: zoo-1
#     ports:
#       - "12181:12181"
#     volumes:
#       - ./data/kafkazoo/zoo1/data:/var/lib/zookeeper/data
#       - ./data/kafkazoo/zoo1/log:/var/lib/zookeeper/log
#     environment:
#       ZOOKEEPER_SERVER_ID: 1
#       ZOOKEEPER_CLIENT_PORT: 12181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 5
#       ZOOKEEPER_SYNC_LIMIT: 2
#       ZOOKEEPER_SERVERS: *zooServers

#   zoo-2:
#     image: confluentinc/cp-zookeeper:latest
#     hostname: zoo-2
#     ports:
#       - "22181:22181"
#     volumes:
#       - ./data/kafkazoo/zoo2/data:/var/lib/zookeeper/data
#       - ./data/kafkazoo/zoo2/log:/var/lib/zookeeper/log
#     environment:
#       ZOOKEEPER_SERVER_ID: 2
#       ZOOKEEPER_CLIENT_PORT: 22181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 5
#       ZOOKEEPER_SYNC_LIMIT: 2
#       ZOOKEEPER_SERVERS: *zooServers

#   zoo-3:
#     image: confluentinc/cp-zookeeper:latest
#     hostname: zoo-3
#     ports:
#       - "32181:32181"
#     volumes:
#       - ./data/kafkazoo/zoo3/data:/var/lib/zookeeper/data
#       - ./data/kafkazoo/zoo3/log:/var/lib/zookeeper/log
#     environment:
#       ZOOKEEPER_SERVER_ID: 3
#       ZOOKEEPER_CLIENT_PORT: 32181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 5
#       ZOOKEEPER_SYNC_LIMIT: 2
#       ZOOKEEPER_SERVERS: *zooServers

#   kafka-1:
#     image: confluentinc/cp-kafka:latest
#     hostname: kafka-1
#     ports:
#       - "19092:19092"
#     volumes:
#       - ./data/kafkazoo/kafka1:/var/lib/kafka/data
#     depends_on:
#       - zoo-1
#       - zoo-2
#       - zoo-3
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: *kafkaZookeeperConnect
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-kafka-1}:19092

#   kafka-2:
#     image: confluentinc/cp-kafka:latest
#     hostname: kafka-2
#     ports:
#       - "29092:29092"
#     volumes:
#       - ./data/kafkazoo/kafka2:/var/lib/kafka/data
#     depends_on:
#       - zoo-1
#       - zoo-2
#       - zoo-3
#     environment:
#       KAFKA_BROKER_ID: 2
#       KAFKA_ZOOKEEPER_CONNECT: *kafkaZookeeperConnect
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-kafka-2}:29092

#   kafka-3:
#     image: confluentinc/cp-kafka:latest
#     hostname: kafka-3
#     ports:
#       - "39092:39092"
#     volumes:
#       - ./data/kafkazoo/kafka3:/var/lib/kafka/data
#     depends_on:
#       - zoo-1
#       - zoo-2
#       - zoo-3
#     environment:
#       KAFKA_BROKER_ID: 3
#       KAFKA_ZOOKEEPER_CONNECT: *kafkaZookeeperConnect
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-kafka-3}:39092
